- name: Advanced loop
  hosts: localhost
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx' , state: 'absent'}
    - {name: 'mailx' , state: 'installed'}
    - {name: 'postfix' , state: 'absent'}