- name: Taking vars from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your username
    private: false
  tasks:
  ansible.builtin.command: id USERNAME
    register: output
    ignore_errors: true
  - name: Print command output
    ansible.builtin.debug:
      msg: "output is {{output}}"
  # - name: print exit status
  #   ansible.builtin.debug:
  #     msg: "Exit staus is {{output.rc}}"
  # - name: create user USERNAME
  #   become: yes
  #   ansible.builtin.user:
  #     name: USERNAME
  #   when: output.rc != 0