- name: create user using conditions
  hosts: localhost

  tasks:
  - name: check roboshop user exist or not
  #to write linux commands directly
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: Print command output
    ansible.builtin.debug:
      msg: "output is {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "Exit staus is {{output.rc}}"
  - name: create user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0