- name: create user using conditions
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
  #to write linux commands directly
  #
    ansible.builtin.command: id roboshop
    register: output
  - name: Print command output
    ansible.builtin.debug:
      msg: "output is {{output}}"