- name: Taking vars from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your username
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks:
  - name: print varaibale values
    ansible.builtin.debug:
      msg: "Username : {{USERNAME}}  and password {{PASSWORD}}"

